import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar.js";
import SessionWrapper from "./components/SessionWrapper.js";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Get Me a Chai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased text-white bg-[#0e112e]`}>
      <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
